cutout_dev/mysite/cutout/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /cutout/
    url(r'^$', views.index, name='index'),
    #url(r'^geturl/$', views.geturl, name='geturl'),
    url(r'^getcutout/(?P<webargs>.*)$', views.getcutout, name='getcutout'),
]

cutout_dev/mysite/jhtdb/urls.py
from django.conf.urls import url
from . import views
#from jhtdb.views import Getcutout

urlpatterns = [
    # ex: /jhtdb/
    url(r'^$', views.index, name='index'),
    #url(r'^geturl/$', views.geturl, name='geturl'),
    url(r'^getcutout/(?P<webargs>.*)$', views.getcutout, name='getcutout'),
    #url(r'^getcutout/(?P<webargs>.*)$', Getcutout.as_view()),
    url(r'^preview/(?P<webargs>.*)$', views.preview, name='preview'),
    url(r'^getprogress/(?P<webargs>.*)$', views.getprogress, name='getprogress'),
    url(r'^poll_for_download/$', views.poll_for_download, name='poll_for_download'),
    url(r'^tests/(?P<webargs>.*)$', views.tests, name='tests'),
]

cutout_dev/mysite/cutout/models.py
from django.db import models

# Create your models here.
class Dataset(models.Model):
    dataset_text = models.CharField(max_length=200)
    dbname_text = models.CharField(max_length=30)
    def __unicode__(self):
        return u'{0}'.format(self.dataset_text)

cutout_dev/mysite/cutout/views.py
from django.shortcuts import render
from django.template import RequestContext, loader
from django.http import HttpResponse
from django.core.files.temp import NamedTemporaryFile
from django import forms
import vtk
import tempfile
import h5py
import zipfile

from .models import Dataset
import odbccutout
# Create your views here.

#def get_filetypes():

class CutoutForm(forms.Form):
    token = forms.CharField(label = 'token', max_length=50)
    fileformat = forms.ChoiceField(choices=[('vtk', 'VTK'), ('hdf5', 'HDF5')])
    dataset = forms.ModelChoiceField(queryset=Dataset.objects.all().order_by('dataset_text'), to_field_name="dbname_text")
    datafields = forms.MultipleChoiceField(choices=[('u', 'Velocity'), ('p',
        'Pressure')])
    cdatafields = forms.ChoiceField(choices=[('', '---------'),
        ('vo', 'Vorticity'),
        ('qc', 'Q-Criterion'),
        ('cvo', 'Vorticity Contour'),
        ('qcc', 'Q-Criterion Contour')])
    timestart = forms.CharField(label =  'timestart', max_length=5)
    timeend = forms.CharField(label =  'timeend', max_length=5)
    x = forms.CharField(label =  'x', max_length=5)
    xEnd = forms.CharField(label =  'xEnd', max_length=5)
    y = forms.CharField(label =  'y', max_length=5)
    yEnd = forms.CharField(label =  'yEnd', max_length=5)
    z = forms.CharField(label =  'z', max_length=5)
    zEnd = forms.CharField(label =  'zEnd', max_length=5)
    tstep = forms.CharField(label =  'tstep', max_length=5, initial="1")
    xstep = forms.CharField(label =  'xstep', max_length=5, initial="1")
    ystep = forms.CharField(label =  'ystep', max_length=5, initial="1")
    zstep = forms.CharField(label =  'zstep', max_length=5, initial="1")
    filter = forms.CharField(label =  'filter', max_length=5, initial="1")
    threshold = forms.CharField(label =  'threshold', max_length=5)
    step_checkbox = forms.BooleanField(label = 'step_checkbox')
    
def index(request):
    dataset_list = Dataset.objects.order_by('dataset_text')
    #output = '<br /> '.join([p.dataset_text for p in dataset_list])
    #return HttpResponse(output)
    template = loader.get_template('cutout/index.html')

    if (request.method == "POST"):    
        token = request.POST.get("token", "")
        ts = request.POST.get("timestart", "")
        te = request.POST.get("timeend", "")
        xs = request.POST.get("x", "")
        xe = request.POST.get("xEnd", "")
        ys = request.POST.get("y", "")
        ye = request.POST.get("yEnd", "")
        zs = request.POST.get("z", "")
        ze = request.POST.get("zEnd", "")
        dataset = request.POST.get("dataset", "")
        datafield = request.POST.getlist("datafields", "")
        datafields = ''.join(datafield)
        if (len(datafield) == 0):
            if (request.POST.get("threshold", "") is None):
                datafields = request.POST.get("cdatafields", "")
            else:
                threshold = request.POST.get("threshold", "")
                datafields = request.POST.get("cdatafields", "") + "," + threshold

        filetype = request.POST.get("fileformat", "")
        server = request.META['HTTP_HOST']
        url = "http://" + server + "/cutout/getcutout/"+ token + "/" + dataset + "/" + datafields + "/" + ts + "," +te + "/" + xs + "," + xe +"/" + ys + "," + ye +"/" + zs + "," + ze + "/" + filetype + "/"
        if (request.POST.get("step_checkbox", "")):
            url = url + "/" + request.POST.get("tstep") + "," + request.POST.get("xstep") + "," + request.POST.get("ystep") + "," + request.POST.get("zstep") + "/" + request.POST.get("filter") 
        download_link = url
        dataset_list = Dataset.objects.order_by('dataset_text')
        form = CutoutForm(request.POST)
        context = RequestContext(request, { 'dataset_list': dataset_list, 'download_link': download_link, 'form': form}) 
    else:
        form = CutoutForm()
        download_link = "Link: " #placeholder until download link is generated
        context = RequestContext(request, { 'dataset_list': dataset_list, 'form': form}) 
    return HttpResponse(template.render(context))
    

def getcutout(request, webargs):
    params = "parameters=%s" % webargs
    w = webargs.split("/")
    ts = int(w[3].split(',')[0])
    te = int(w[3].split(',')[1])
    #o = odbccutout.OdbcCutout()
    if ((len(w) >= 8) and (w[7] == 'vtk')):    
        #Setup temporary file (would prefer an in-memory buffer, but this will have to do for now)
        if (len(w) >= 10):
            tspacing = int(w[8].split(",")[0])
        else:
            tspacing = 1
        cfieldlist = w[2].split(",")
        firstval = cfieldlist[0]
        if ((firstval == 'cvo') or (firstval == 'qcc')): #we may need to return a vtp file
            tmp = NamedTemporaryFile(suffix='.vtp')
            suffix = 'vtp'
            writer = vtk.vtkXMLPolyDataWriter()                         
            outfile = w[7] + '-contour'
        elif (w[1] == "channel"):
	    tmp = NamedTemporaryFile(suffix='.vtr')
	    suffix = 'vtr'
	    writer = vtk.vtkXMLRectilinearGridWriter()
	    outfile = 'cutout' + w[7]
        else:
            tmp = NamedTemporaryFile(suffix='.vti')
            suffix = 'vti'
            writer = vtk.vtkXMLImageDataWriter()                        
            outfile = 'cutout' + w[7]        
        writer.SetFileName(tmp.name)
        writer.SetCompressorTypeToZLib()
        writer.SetDataModeToBinary()
        #if multiple timesteps, zip the file.
        if ((te-ts) > 1):
            #Write each timestep to file and read it back in.  Seems to be the only way I know how to put all timesteps in one file for now
            #Create a timestep for each file and then send the user a zip file
            ziptmp = NamedTemporaryFile(suffix='.zip')
            z = zipfile.ZipFile(ziptmp.name, 'w')
            for timestep in range (ts,te, tspacing ):            
                image = odbccutout.OdbcCutout().getvtkimage(webargs, timestep)
                writer.SetInputData(image)
                writer.SetFileName(tmp.name)                        
                writer.Write()
                #Now add this file to the zipfile
                z.write(tmp.name, 'cutout' + str(timestep) + '.' + suffix)
            z.close()
            ct = 'application/zip'
            suffix = 'zip'
            response = HttpResponse(ziptmp, content_type=ct)

        else:
            image = odbccutout.OdbcCutout().getvtkimage(webargs, ts)
            writer.SetInputData(image)
            writer.SetFileName(tmp.name)                        
            writer.Write()
            ct = 'data/vtk'
            response = HttpResponse(tmp, content_type=ct)
        response['Content-Disposition'] = 'attachment;filename=' +  outfile +'.' + suffix
    else: #for backward compatibility, we serve hdf5 if not specified
        #Create an HDF5 file here
        h5file = odbccutout.OdbcCutout().gethdf(webargs)
        response = HttpResponse(h5file, content_type='data/hdf5')
        attach = 'attachment;filename=' + w[1] + '.h5'
        response['Content-Disposition'] = attach

    return response
    #return HttpResponse(result)

cutout_dev/mysite/cutout/templates/cutout/index.html
<html xmlns="http://www.w3.org/1999/xhtml">
<head><title>Johns Hopkins Turbulence Databases (JHTDB)</title>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
Turbulence Expanded cutout service
<script type="text/javascript" src="/static/scripts/chosen.jquery.min.js"></script>
<link rel="stylesheet" href="/static/scripts/chosen.css">
<style>
#id_dataset {
    width: 250px;
}
#id_fileformat {
    width: 80px;
}
#id_datafields {
    width: 350px;
}
#id_x {
    width: 40px;
}
#id_y {
    width: 40px;
}
#id_z {
    width: 40px;
}
#id_timestart {
    width: 40px;
}
#id_timeend {
    width: 40px;
}
#id_xEnd {
    width: 40px;
}
#id_yEnd {
    width: 40px;
}
#id_zEnd {
    width: 40px;
}
#id_threshold {
    width: 40px;
}
#id_filter {
    width: 40px;
}

</style>
</head>
<form method="POST" />{% csrf_token %}
<table>
<tr><td>Authorization Token:</td><td>
{{form.token}}

</td></tr>
<tr><td>Select Dataset:</td>
<td>

{{form.dataset}}

</td></tr>

<tr><td>Data Field(s):  </td>
<td>
{{form.datafields}}

</td></tr>
<td></td><td>Or choose a computed field (VTK Only):
{{form.cdatafields}}

<span id="threshold">
Threshold: {{form.threshold}}
</span>

</td></tr>
<tr><td>File Format</td>
<td>
{{form.fileformat}}


</td></tr>
</table>
<table>
 
<tr>

            <td valign="top" colspan="2">Starting coordinate <br /> index for cutout: [<a href="/datasets.aspx" class="note">?</a>] </td>

            <td valign="top" colspan="2"> &nbsp;Size of cutout: [<a href="/datasets.aspx" class="note">?</a>] <br />

                <span class="style1"> &nbsp;(end index minus start index + 1)</span> </td>            

            <td class="style35" valign="top" colspan="2">

                {{form.step_checkbox}}

                <span id="stepCell" title="Optionally select a step size. If omitted every point in the range will be returned."> &nbsp;

                    <span >Step (optional) :</span>

                </span> 

            </td>

        </tr>

        <tr>

            <td  >m<sub>t</sub> <span id="time_start_range"></span>: </td>

            <td > {{form.timestart}} <br /> </td>

            <td  > &nbsp;M<sub>t</sub> <span id="time_end_range"></span>: </td>

            <td > {{form.timeend}} <br /> </td>

           <td >  </td> <td class="step">s<sub>t</sub>:{{form.tstep}} </td>

            

            <td  rowspan="4">  

                 </td>

         </tr>

         <tr>

            <td  > i<sub>x</sub> <span id="x_start_range"></span>:  </td>

            <td > {{form.x}} <br /> </td>

            <td  > &nbsp;N<sub>x</sub> <span id="x_end_range"></span>:  </td>

            <td > {{form.xEnd}} <br /> </td>

            <td >  </td><td class="step">s<sub>x</sub>:{{form.xstep}} </td>

             

         </tr>

         <tr>

            <td  > j<sub>y</sub> <span id="y_start_range"></span>:  </td>

            <td > {{form.y}}<br /> </td>

            <td  > &nbsp;N<sub>y</sub> <span id="y_end_range"></span>:  </td>

            <td > {{form.yEnd}}<br /> </td>

            <td >  </td><td class="step">s<sub>y</sub>:{{form.ystep}} </td>

             

         </tr>

         <tr>

            <td  > k<sub>z</sub> <span id="z_start_range"></span>:  </td>

            <td > {{form.z}} </td>

            <td  > &nbsp;N<sub>z</sub> <span id="z_end_range"></span>:  </td>

            <td > {{form.zEnd}} </td>

            <td >  </td><td class="step">s<sub>z</sub>:{{form.zstep}} </td>

            

         </tr>    
</table><br />
<span class="step">
Filter Width (optional): {{form.filter}}</span>
<br />
<input type="submit" name="Submit" Value="Submit Cutout Parameters" />
</form>
<div id="download_link"><a href='{{download_link}}'>{{download_link}}</a></div> 
<script>
$("#id_dataset").chosen();
$("#id_datafields").chosen();
$("#id_cdatafields").chosen();
$("#id_fileformat").chosen();
$('.step').hide();

$(document).ready(function() {
  if($("#id_step_checkbox").is(':checked')){ 
    $('.step').show();
  }
  if ($("#id_cdatafields").val() == "cvo") {
      $('#threshold').show();
  }
  else if ($("#id_cdatafields").val() == "qcc") {
      $('#threshold').show();
  }
  else {
      $('#threshold').hide();
  }
  //$('#id_dataset').trigger('change');
  //We can't do the above because it clears out the data fields.

});


$('#id_step_checkbox').on('change', function() {    
   var val = $(this).val();
   if ($(this).is(":checked"))
   $('.step').show();  
  else
   $('.step').hide();
});


$('#id_datafields').on('change', function() {
   var dset= $(this).val();
   //Clear out any values on computed fields
   $(function() {$("#id_cdatafields").val("none");
    });
  $('#id_cdatafields').trigger('chosen:updated');
});


$('#id_cdatafields').on('change', function() {
   var dset= $(this).val();
   //Clear out any values on data fields
   $(function() {$("#id_datafields").val([]);
    });
    $('#id_datafields').trigger('chosen:updated');
      if (dset == "cvo") {
          $('#threshold').show();
      }
      else if (dset == "qcc") {
          $('#threshold').show();
      }
      else {
          $('#threshold').hide();

      }

});

$('#id_fileformat').on('change', function() {
   var ftype= $(this).val();
   if (ftype == 'hdf5')
       //Clear out any values on computed fields
       $(function() {$("#id_cdatafields").val([]);
        });
        $('#id_cdatafields').trigger('chosen:updated');
});


$('#id_dataset').on('change', function() {
   var dset= $(this).val();
   //Clear out any values 
   //alert('changed');
   $("#id_datafields").find('option').remove();
   if (dset == 'isotropic1024coarse'){
      $("#id_datafields").append($("<option>", {value: 'u', text: 'Velocity'}));
      $("#id_datafields").append($("<option>", {value: 'p', text: 'Pressure'})); 
      $("#time_start_range").text("(0-1024)");
      $("#time_end_range").text("(1-1025)");
      $("#x_start_range").text("(0-1023)");
      $("#x_end_range").text("(1-1024)");
      $("#y_start_range").text("(0-1023)");
      $("#y_end_range").text("(1-1024)");
      $("#z_start_range").text("(0-1023)");
      $("#z_end_range").text("(1-1024)");
    } 
   else if (dset == 'isotropic1024fine'){
      $("#id_datafields").append($("<option>", {value: 'u', text: 'Velocity'}));
      $("#id_datafields").append($("<option>", {value: 'p', text: 'Pressure'})); 
      $("#time_start_range").text("(0-1024)");
      $("#time_end_range").text("(1-100)");
      $("#x_start_range").text("(0-1023)");
      $("#x_end_range").text("(1-1024)");
      $("#y_start_range").text("(0-1023)");
      $("#y_end_range").text("(1-1024)");
      $("#z_start_range").text("(0-1023)");
      $("#z_end_range").text("(1-1024)");
 
    }
   else if (dset == 'channel'){
      $("#id_datafields").append($("<option>", {value: 'u', text: 'Velocity'}));
      $("#id_datafields").append($("<option>", {value: 'p', text: 'Pressure'})); 
      $("#time_start_range").text("(0-3999)");
      $("#time_end_range").text("(1-4000)");
      $("#x_start_range").text("(0-2047)");
      $("#x_end_range").text("(1-2048)");
      $("#y_start_range").text("(0-511)");
      $("#y_end_range").text("(1-512)");
      $("#z_start_range").text("(0-1535)");
      $("#z_end_range").text("(1-1536)");
    }
   else if (dset == 'mhd1024'){
      $("#id_datafields").append($("<option>", {value: 'u', text: 'Velocity'}));
      $("#id_datafields").append($("<option>", {value: 'p', text: 'Pressure'}));
      $("#id_datafields").append($("<option>", {value: 'b', text: 'Magnetic Field'}));
      $("#id_datafields").append($("<option>", {value: 'a', text: 'VectorPotential'})); 
      $("#time_start_range").text("(0-1024)");
      $("#time_end_range").text("(1-1025)");
      $("#x_start_range").text("(0-1023)");
      $("#x_end_range").text("(1-1024)");
      $("#y_start_range").text("(0-1023)");
      $("#y_end_range").text("(1-1024)");
      $("#z_start_range").text("(0-1023)");
      $("#z_end_range").text("(1-1024)");
    } 
    else if (dset == 'mixing'){
      $("#id_datafields").append($("<option>", {value: 'u', text: 'Velocity'}));
      $("#id_datafields").append($("<option>", {value: 'p', text: 'Pressure'}));
      $("#id_datafields").append($("<option>", {value: 'd', text: 'Density'}));
      $("#time_start_range").text("(0-1011)");
      $("#time_end_range").text("(1-1025)");
      $("#x_start_range").text("(0-1012)");
      $("#x_end_range").text("(1-1024)");
      $("#y_start_range").text("(0-1023)");
      $("#y_end_range").text("(1-1024)");
      $("#z_start_range").text("(0-1023)");
      $("#z_end_range").text("(1-1024)");
    }

   
   $('#id_datafields').trigger('chosen:updated');
});
</script>